### ISSUE TITLE
HTTP Forbidden issue when installing/updating games and viewing info

### ISSUE THREAD

**Issue by TobySear** [derrod/legendary#479]
## Platform

Operating system and version: Ubuntu 20.04.5 LTS, legendary installed through pip
Legendary version (`legendary -V`): legendary version "0.20.28", codename "Dark Energy (hotfix #2)"

## Expected Behavior

Running commands:

- legendary install Sugar
- legendary info Sugar
- legendary install bc2c95c6ff564a16b26644f1d3ac3c55
- legendary install 47b70f27b76747cdaaff7757712b8248

Should install the supplied game or provide the game info.

## Current Behavior

At present all info and install commands result in an error similar to below:
`[Core] INFO: Trying to re-use existing login session...
[cli] INFO: Preparing download for "Rocket League®" (Sugar)...
Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/legendary/cli.py", line 2971, in main
    cli.install_game(args)
  File "/usr/local/lib/python3.8/dist-packages/legendary/cli.py", line 931, in install_game
    dlm, analysis, igame = self.core.prepare_download(game=game, base_game=base_game, base_path=args.base_path,
  File "/usr/local/lib/python3.8/dist-packages/legendary/core.py", line 1296, in prepare_download
    new_manifest_data, base_urls = self.get_cdn_manifest(game, platform, disable_https=disable_https)
  File "/usr/local/lib/python3.8/dist-packages/legendary/core.py", line 1221, in get_cdn_manifest
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.epicgames.com/Builds/Org/[Full URL Snipped]`

## Steps to Reproduce

1. Install legendary
2. Login to legendary with an account which has Rocket League
3. Run `legendary install Sugar`
4. View HTTP 403 error

## Additional information

We have seen the same results on 2 machines with 3 accounts. We are able to install games fine through the epic games launcher.
Many thanks for your development and continued support of Legendary, its a great piece of software.

**Comment by TobySear** [comment]
I see this is being resolved by PR 477: https://github.com/derrod/legendary/pull/477
Thanks for your support in getting this fixed.

**Comment by nutterthanos** [comment]
Odd how EGL is fine but legendary has intermittent failure

**Comment by CommandMC** [comment]
> Odd how EGL is fine but legendary has intermittent failure

Well, the EGL does the same thing that is now done in that PR: Trying all available CDNs until one works.
@derrod shared this picture on the Heroic discord earlier today showing this behavior:
![image](https://user-images.githubusercontent.com/34034631/189357473-f641c10a-519c-4107-8626-512a76648601.png)

So even if it *wouldn't* fix this issue, it's still good practice to be in-line with how the EGL works

**Comment by aadityadhruv** [comment]
I am also getting the same error. On Fedora 36 with Kernel 5.19.

**Comment by Trokinos** [comment]
I get this error 403 on window 10 (current version of legendary.exe) too when trying to install "Vampyr".  

Previously today i was trying to install the current epic store freebie , "Hundred Days Winemaking Simulator" and got the same error, but it worked a dozen of minutes later.   But for Vampyr (Nautilus is the game name code for it) it's still no go at all.

`C:\Legendary\legendary.exe install Nautilus`
`[Core] INFO: Trying to re-use existing login session...`
`[cli] INFO: Preparing download for "Vampyr" (Nautilus)...`
`Traceback (most recent call last):`
`  File "legendary\cli.py", line 3054, in <module>`
`  File "legendary\cli.py", line 2971, in main`
`  File "legendary\cli.py", line 931, in install_game`
`  File "legendary\core.py", line 1296, in prepare_download`
`  File "legendary\core.py", line 1221, in get_cdn_manifest`
`  File "requests\models.py", line 1021, in raise_for_status`
`requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.epicgames.com/............blablablalongserieofvariouscharactersandglyphs`
`[2984] Failed to execute script 'cli' due to unhandled exception!`

**Comment by nutterthanos** [comment]
launcher-public-service api is spiting out broken signature's for downloadx.epicgames.com cdn unless like amazon/epic broke something elsewhere 🤷

**Comment by derrod** [comment]
Fixed by 0eec8472a446eb64806c84c2671ac41eca20eef5 in 0.20.29.

**Comment by DonFlymoor** [comment]
Nice, now it works
